/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;
import Login.*;
import java.awt.Toolkit;

/**
 *
 * @author Nesty
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public DashboardFrame() {
        initComponents();
        
        //fixed frame
        this.setResizable(false); 
        //Set Icon image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("MotorIcon.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIS = new javax.swing.JTextField();
        jTextFieldEnum1 = new javax.swing.JTextField();
        jTextFieldFullName = new javax.swing.JTextField();
        jTextFieldBirthday = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPhoneN = new javax.swing.JTextField();
        jTextFieldSSSN = new javax.swing.JTextField();
        jTextFieldPhilN = new javax.swing.JTextField();
        jTextFieldPagN = new javax.swing.JTextField();
        jTextFieldTaxID = new javax.swing.JTextField();
        jTextFieldStat = new javax.swing.JTextField();
        jTextFieldPOS = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableinfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Employee Dashboard");
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MotorIcon2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee Number", "Full Name", "Birthday", "Address" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 290, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 80));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1130, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 102, 102))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Intermediate Supervisor");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Employee Number");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Full Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Birthday");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Address");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, -1));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Phone Number");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, -1));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("SSS Number");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Philhealth Number");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, -1));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Pagibig Number");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("Tax Identification Number");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, -1));

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("Status");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("Position");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, -1));

        jTextFieldIS.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 180, -1));

        jTextFieldEnum1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldEnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnum1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldEnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, -1));

        jTextFieldFullName.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFullNameActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, -1));

        jTextFieldBirthday.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdayActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        jTextFieldAddress.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, -1));

        jTextFieldPhoneN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldPhoneN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldPhoneN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, -1));

        jTextFieldSSSN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldSSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSSNActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldSSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 240, -1));

        jTextFieldPhilN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldPhilN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilNActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldPhilN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 220, -1));

        jTextFieldPagN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldPagN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagNActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldPagN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, -1));

        jTextFieldTaxID.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldTaxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaxIDActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldTaxID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, -1));

        jTextFieldStat.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, -1));

        jTextFieldPOS.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jTextFieldPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPOSActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 290, -1));

        jButtonClear.setBackground(new java.awt.Color(255, 102, 102));
        jButtonClear.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jButtonClear.setText("CLEAR");
        jPanel4.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jButtonAdd.setBackground(new java.awt.Color(255, 102, 102));
        jButtonAdd.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jButtonAdd.setText("ADD");
        jPanel4.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 70, -1));

        jButtonUpdate.setBackground(new java.awt.Color(255, 102, 102));
        jButtonUpdate.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jButtonUpdate.setText("UPDATE");
        jPanel4.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jButtonDelete.setText("DELETE");
        jPanel4.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jTableinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Birthday", "Address", "Phone Number", "SSS Number", "Philhealth Number", "Pagibig Number", "Tax Identification Number", "Status", "Position", "Supervisor"
            }
        ));
        jScrollPane1.setViewportView(jTableinfo);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 700, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1120, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 609));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISActionPerformed

    private void jTextFieldEnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnum1ActionPerformed

    private void jTextFieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFullNameActionPerformed

    private void jTextFieldBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdayActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldPhoneNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNActionPerformed

    private void jTextFieldSSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSSNActionPerformed

    private void jTextFieldPhilNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilNActionPerformed

    private void jTextFieldPagNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagNActionPerformed

    private void jTextFieldTaxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaxIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaxIDActionPerformed

    private void jTextFieldStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatActionPerformed

    private void jTextFieldPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableinfo;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBirthday;
    private javax.swing.JTextField jTextFieldEnum1;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldIS;
    private javax.swing.JTextField jTextFieldPOS;
    private javax.swing.JTextField jTextFieldPagN;
    private javax.swing.JTextField jTextFieldPhilN;
    private javax.swing.JTextField jTextFieldPhoneN;
    private javax.swing.JTextField jTextFieldSSSN;
    private javax.swing.JTextField jTextFieldStat;
    private javax.swing.JTextField jTextFieldTaxID;
    // End of variables declaration//GEN-END:variables
}
